CREATE TABLE wines (
  id SERIAL PRIMARY KEY,
  photo TEXT NOT NULL,
  rating FLOAT NOT NULL,
  comment TEXT
);

-- 检查users表是否已存在,如果不存在则创建
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
